In [2]:
import pandas as pd

In [3]:
url = 'https://raw.githubusercontent.com/NRSchaaf/Railroad_Accidents/refs/heads/main/RR_Accident_Weather_Data.csv'
df = pd.read_csv(url)

In [4]:
df.head()

,reportingrailroadcode,accidentnumber,date,time,accidenttype,hazmatreleasedcars,station,stateabbr,temperature,visibility_code,...,trainspeed,equipmentdamagecost,trackdamagecost,totaldamagecost,primaryaccidentcausecode,latitude,longitude,prior_temp,actual_temp,following_temp
0,CSX,000178042,8/7/2018,10:51 AM,Derailment,0,BUFFALO,NY,73,2,...,6,19801,1440,21241,T001,42.901973,-78.773441,79.3,75.1,72.4
1,CSX,000182665,4/30/2019,12:25 AM,Derailment,0,MILLBURY,OH,42,4,...,7,21848,1017,22865,T111,41.544006,-83.485654,44.3,45.5,56.6
2,CSX,000138406,12/3/2014,11:45 PM,Derailment,0,PARMA,OH,35,4,...,7,20456,500,20956,T110,41.406978,-81.787482,30.0,34.7,30.4
3,CSX,000188525,2/19/2020,8:44 AM,Derailment,0,CINCINNATI,OH,25,2,...,0,84949,0,625123,T207,39.125335,-84.540044,48.2,34.9,29.7
4,CSX,000175393,3/24/2018,10:53 AM,Derailment,0,LIMA,OH,36,2,...,7,115993,0,196239,T311,40.745354,-84.101095,33.6,31.3,31.8

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4595 entries, 0 to 4594
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   reportingrailroadcode     4595 non-null   object
 1   accidentnumber            4595 non-null   object
 2   date                      4595 non-null   object
 3   time                      4595 non-null   object
 4   accidenttype              4595 non-null   object
 5   hazmatreleasedcars        4595 non-null   int64
 6   station                   4595 non-null   object
 7   stateabbr                 4595 non-null   object
 8   temperature               4595 non-null   int64
 9   visibility_code           4595 non-null   int64
 10  visibility                4595 non-null   object
 11  weathercondition          4595 non-null   object
 12  tracktype                 4595 non-null   object
 13  equipmenttype             4303 non-null   object
 14  trainspeed                4595 non-null   int64
 15  equipmentdamagecost       4595 non-null   int64
 16  trackdamagecost           4595 non-null   int64
 17  totaldamagecost           4595 non-null   int64
 18  primaryaccidentcausecode  4595 non-null   object
 19  latitude                  4595 non-null   float64
 20  longitude                 4595 non-null   float64
 21  prior_temp                4595 non-null   float64
 22  actual_temp               4595 non-null   float64
 23  following_temp            4595 non-null   float64
dtypes: float64(5), int64(7), object(12)
memory usage: 861.7+ KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
hazmatreleasedcars,4595.0,0.028945,0.526021,0.00000,0.000000,0.000000,0.000000,2.800000e+01
temperature,4595.0,58.926877,22.587870,-35.00000,41.000000,60.000000,77.000000,1.150000e+02
visibility_code,4595.0,2.660936,1.035686,1.00000,2.000000,2.000000,4.000000,4.000000e+00
trainspeed,4595.0,9.551687,12.077753,0.00000,4.000000,6.000000,9.000000,1.250000e+02
equipmentdamagecost,4595.0,114259.902938,448682.514449,0.00000,5282.500000,19123.000000,63174.500000,2.194712e+07
trackdamagecost,4595.0,67180.249837,202218.147279,0.00000,1857.000000,12000.000000,47450.000000,4.600000e+06
totaldamagecost,4595.0,208355.717954,664294.973831,0.00000,20940.500000,48135.000000,144222.500000,2.201925e+07
latitude,4595.0,37.919532,5.213919,0.00000,33.741081,39.110705,41.412739,4.901675e+01
longitude,4595.0,-92.067926,15.604322,-683.19219,-97.353523,-90.605520,-83.505282,0.000000e+00
prior_temp,4595.0,57.591077,19.029285,-16.80000,42.150000,59.700000,74.100000,1.002000e+02
actual_temp,4595.0,57.371121,19.353664,-18.80000,42.100000,59.200000,74.000000,1.001000e+02
following_temp,4595.0,57.465484,19.380081,-21.20000,42.700000,59.100000,74.400000,1.029000e+02

In [7]:
derailment_count = df[df['accidenttype'] == 'Derailment'].shape[0]
derailment_count

4301